// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using calendar_backend.Models.DbContexts;

namespace calendar_backend.Migrations.CustomizationPresetsDb
{
    [DbContext(typeof(CustomizationPresetsDbContext))]
    partial class CustomizationPresetsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("calendar_backend.Models.CustomizationPreset", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("BottomPanelScrollDistance")
                        .HasColumnType("int");

                    b.Property<int>("BottomPanelScrollSpeed")
                        .HasColumnType("int");

                    b.Property<string>("CompellingColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FontFamily")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImportantColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrdinaryColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PresetName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UpperPanelScrollSpeed")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CustomizationPresets");
                });
#pragma warning restore 612, 618
        }
    }
}
