export const GET_EVENTS_START = 'GET_EVENTS_START';
export const GET_EVENTS = 'GET_EVENTS';

export const SET_SELECTED_ELEMENT_INDEX = 'SET_SELECTED_ELEMENT_INDEX';

export const SET_CUSTOMIZATIONS = 'SET_CUSTOMIZATIONS';

export const SET_DAYS_TO_SHOW = 'SET_DAYS_TO_SHOW';

export const GET_GRAPH_INFO = 'GET_GRAPH_INFO';

export const DELETE_PRESET = 'DELETE_PRESET';
export const DELETE_PRESET_START = 'DELETE_PRESET_START';
export const GET_PRESETS = 'GET_PRESETS';
export const GET_PRESETS_START = 'GET_PRESETS_START';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS';
export const GET_USER_INFO_ERROR = 'GET_USER_INFO_ERROR';

export const SET_TUTORIAL_STAGE = 'SET_TUTORIAL_STAGE';
